apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: exnaton-mysql-init-volume-class
provisioner: k8s.io/minikube-hostpath
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: false
