apiVersion: apps/v1
kind: Deployment
metadata:
  name: exnaton-seq
  namespace: 1db7649e-9342-4e04-97c7-f0ebb88ed1f8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exnaton-seq
  template:
    metadata:
      labels:
        app: exnaton-seq
    spec:
      containers:
        - name: exnaton-seq
          image: datalust/seq:latest
          ports:
            - containerPort: 5341
            - containerPort: 80
          env:
            - name: ACCEPT_EULA
              value: "Y"
---
apiVersion: v1
kind: Service
metadata:
  name: exnaton-seq-service
  namespace: 1db7649e-9342-4e04-97c7-f0ebb88ed1f8
spec:
  selector:
    app: exnaton-seq
  ports:
    - name: ingestion
      protocol: TCP
      port: 5341
      targetPort: 5341  
    - name: web
      protocol: TCP
      port: 8001
      targetPort: 80
  type: NodePort
