apiVersion: apps/v1
kind: Deployment
metadata:
  name: exnaton-webapi
  namespace: 1db7649e-9342-4e04-97c7-f0ebb88ed1f8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exnaton-webapi
  template:
    metadata:
      labels:
        app: exnaton-webapi
    spec:
      containers:
        - name: exnaton-webapi
          image: exnaton-webapi:lts
          env:
            - name: ASPNETCORE_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: exnaton-config
                  key: ASPNETCORE_ENVIRONMENT
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  name: exnaton-config
                  key: MYSQL_HOST
            - name: MYSQL_PORT
              valueFrom:
                configMapKeyRef:
                  name: exnaton-config
                  key: MYSQL_PORT
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: exnaton-config
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: exnaton-secret
                  key: MYSQL_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: exnaton-config
                  key: MYSQL_DATABASE
            - name: SEQ_URL
              valueFrom:
                configMapKeyRef:
                  name: exnaton-config
                  key: SEQ_URL
          ports:
            - containerPort: 5142
---
apiVersion: v1
kind: Service
metadata:
  name: exnaton-webapi-service
  namespace: 1db7649e-9342-4e04-97c7-f0ebb88ed1f8
spec:
  selector:
    app: exnaton-webapi
  ports:
    - name: web
      protocol: TCP
      port: 5142
      targetPort: 5142
  type: NodePort
