version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: exnaton_mysql
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - exnaton_mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - exnaton_network
  
  seq:
    image: datalust/seq:latest
    container_name: exnaton_seq
    restart: always
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 8081:80
    networks:
      - exnaton_network
 

volumes:
  exnaton_mysql_data:

networks:
  exnaton_network:
    driver: bridge
    external: false

