apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-primary
  namespace: shared-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      role: primary
  template:
    metadata:
      labels:
        app: mysql
        role: primary
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: password
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-replica
  namespace: shared-services
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mysql
      role: replica
  template:
    metadata:
      labels:
        app: mysql
        role: replica
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          env:
            - name: MYSQL_REPLICATION_MODE
              value: "replica"
            - name: MYSQL_MASTER_HOST
              value: "mysql-primary"
